### ISSUE TITLE
UML diagrams don't work

### ISSUE THREAD

**Issue by ales-tsurko** [Moneyfactory-io/blockscout-frontend#8]
When we try to open a UML diagram it responds with 500 error code. Please, check the console for more info.

This is how it should look like: https://gnosis.blockscout.com/visualize/sol2uml?address=0x79e32aE03fb27B07C89c0c568F80287C01ca2E57

And this is what we get:
<img width="956" alt="Screenshot 2024-03-29 at 12 04 07" src="https://github.com/Atleta-network/blockscout/assets/8686568/10478479-b7f5-4417-b09d-6cd88f48d4aa">

**Comment by r8bywork** [comment]
Title: "400 Error on UML Diagrams Page Due to Incorrect Microservice Configuration"

Description:
We've encountered a 400 error on the page displaying UML diagrams, indicating that the server is unable to process the request properly. This issue stems from an incorrect host URL configuration in the microservice responsible for generating UML diagrams for smart contracts.

To resolve this, it's essential to ensure the microservice is correctly configured with the appropriate host URL.

Expected Configuration:
- The `MICROSERVICE_VISUALIZE_SOL2UML_ENABLED` environment variable should be set to true.
- The `MICROSERVICE_VISUALIZE_SOL2UML_URL` environment variable should point to our server's host, not `visualizer`.

Configuration Files:
- Environment variables in `deploy/envs/common-blockscout.env`.
- Microservice configuration in `deploy/services/visualizer.yml`.
- deploy/proxy/default.conf.template (change proxy_pass http://visualizer:8050/)
- deploy/proxy/microservices.conf.template (change proxy_pass http://visualizer:8050/)
